[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[invariant]
runs = 1000
depth = 128 #number of calls in a single run
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
